"""Report generation helper.

This module emits a *machine-readable* metrics snapshot (default destination
``reports/lab_report_auto.md``). The hand-written deliverable lives at
``reports/lab_report.md`` and is preserved between runs by pointing ``report_path`` at
the ``*_auto.md`` filename in :file:`configs/lab.yaml`.
"""

from __future__ import annotations

from pathlib import Path

from .metrics import MetricsReport


def render_report_stub(metrics: MetricsReport) -> str:
    """Render a compact metrics snapshot in Markdown."""
    rows = "\n".join(
        f"| {m.scenario_id} | {m.expected_route} | {m.actual_route or '-'} | "
        f"{'OK' if m.success else 'FAIL'} | {m.retry_count} | {m.interrupt_count} | "
        f"{m.nodes_visited} | {m.latency_ms} |"
        for m in metrics.scenario_metrics
    )
    return f"""# Day 08 Lab — Auto Metrics Snapshot

This file is regenerated by `langgraph_agent_lab.cli run-scenarios`. The narrative report
lives at [lab_report.md](lab_report.md).

## Summary

- Total scenarios: {metrics.total_scenarios}
- Success rate: {metrics.success_rate:.2%}
- Average nodes visited: {metrics.avg_nodes_visited:.2f}
- Total retries: {metrics.total_retries}
- Total interrupts: {metrics.total_interrupts}
- Resume success: {metrics.resume_success}

## Per-scenario

| ID | Expected | Actual | Success | Retries | Interrupts | Nodes | Latency (ms) |
|---|---|---|:-:|--:|--:|--:|--:|
{rows}
"""


def write_report(metrics: MetricsReport, output_path: str | Path) -> None:
    """Persist the auto-generated metrics snapshot to ``output_path``."""
    path = Path(output_path)
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(render_report_stub(metrics), encoding="utf-8")
